name: flutter_prova1
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  intl: ^0.17.0
  iconsax: ^0.0.8
  shared_preferences: ^2.2.3
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
